- name: My Super Pooper Playbook
  hosts: all
  become: yes

  vars:
    msg1: "First message"
    msg2: Hello
    secret: JHGUIJOHKGUYIUOHJKGIYUHOJ

  tasks:
    
    - name: Print secret text
      debug:
        var: secret

    - debug:
        msg: "Sekretnoe slovo: {{ secret }}"


    - set_fact:
        full_msg="{{ msg2 }} - {{ msg1 }} ({{ secret }})"

    - debug:
        var: full_msg

    - debug:
        var: ansible_distribution

    - shell: uptime
      register: server_uptime

    - debug:
        var: server_uptime.stdout


